/**
 * <p>Provides classes representing information for inclusion in the search results page generated by the Curator system.</p>
 * 
 * @since 13.0
 */
package com.funnelback.curator.action.data;

