<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="robots" content="noindex,nofollow" />

    <title>Form not found</title>

	<style type="text/css">
		body {
			font-family: Verdana;
			text-align: center;
		}
    </style>

</head>

<body>

    <#-- DO NOT EDIT THIS FILE DIRECTLY

    It will get overwritten during an upgrade. If you need to customise this page,
    copy it to form-not-found.ftl

    -->

    <h1>Search Error</h1> 

    <p>We're sorry, the <code>${(question.form)!form!}</code> form does not exist, please try a different form (e.g. form=simple)</p>

</body>
</html>
